In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

In [2]:
#scaler 
torch.tensor(5)

tensor(5)

In [3]:
!python --version
!conda --version


Python 3.10.9
conda 23.1.0


In [4]:
import sys
print(sys.executable)

/home/ishaque/anaconda3/bin/python


In [5]:
scaler =torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim

0

In [7]:
scaler.item()

7

In [8]:
vector = torch.tensor([12,34,3])

In [9]:
vector.ndim

1

In [10]:
# random tensor 
random_tensor = torch.rand(3,4)
random_tensor

tensor([[4.6976e-01, 1.4267e-01, 1.0001e-01, 9.0885e-04],
        [4.5737e-02, 3.0616e-01, 9.8200e-01, 8.6826e-01],
        [2.0582e-01, 8.2089e-01, 5.1814e-01, 3.0142e-01]])

In [11]:
random_image_size_tensor = torch.rand(224,224,3)

In [12]:
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [13]:
random_tansor = torch.rand(3,4)
random_tensor

tensor([[4.6976e-01, 1.4267e-01, 1.0001e-01, 9.0885e-04],
        [4.5737e-02, 3.0616e-01, 9.8200e-01, 8.6826e-01],
        [2.0582e-01, 8.2089e-01, 5.1814e-01, 3.0142e-01]])

In [14]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
# usiing arange function 
one_to_ten = torch.arange(start=1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# creating tensor using like 

ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
#detail about tensor 
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7569, 0.1295, 0.5941, 0.3174],
        [0.0831, 0.6256, 0.2126, 0.7964],
        [0.7163, 0.9126, 0.0135, 0.2763]])

In [21]:
# showing details about tensor 
print(f"tensor datatype {some_tensor.dtype}")
print(f"tensor shape {some_tensor.shape}")
print(f"device that tensor is on {some_tensor.device}")

tensor datatype torch.float32
tensor shape torch.Size([3, 4])
device that tensor is on cpu


In [1]:
#create tensor 
tensor = torch.tensor([2,3,4])
tensot +19

NameError: name 'torch' is not defined