In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

Matplotlib is building the font cache; this may take a moment.


2.0.0+cpu


In [2]:
#scaler 
torch.tensor(5)

tensor(5)

In [5]:
!python --version
!conda --version


Python 3.10.9
conda 23.1.0


In [6]:
import sys
print(sys.executable)

/home/ishaque/anaconda3/bin/python


In [7]:
scaler =torch.tensor(7)
scaler

tensor(7)

In [8]:
scaler.ndim

0

In [9]:
scaler.item()

7

In [10]:
vector = torch.tensor([12,34,3])

In [15]:
vector.ndim

1

In [16]:
# random tensor 
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3594, 0.5701, 0.0675, 0.9658],
        [0.1016, 0.5430, 0.0432, 0.7745],
        [0.5903, 0.9796, 0.7433, 0.1375]])

In [17]:
random_image_size_tensor = torch.rand(224,224,3)

In [21]:
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [24]:
random_tansor = torch.rand(3,4)
random_tensor

tensor([[0.3594, 0.5701, 0.0675, 0.9658],
        [0.1016, 0.5430, 0.0432, 0.7745],
        [0.5903, 0.9796, 0.7433, 0.1375]])

In [26]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# usiing arange function 
one_to_ten = torch.arange(start=1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# creating tensor using like 

ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])