In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cpu


In [3]:
#scaler 
torch.tensor(5)

tensor(5)

In [4]:
!python --version
!conda --version


Python 3.10.9
conda 23.1.0


In [5]:
import sys
print(sys.executable)

/home/ishaque/anaconda3/bin/python


In [6]:
scaler =torch.tensor(7)
scaler

tensor(7)

In [7]:
scaler.ndim

0

In [8]:
scaler.item()

7

In [9]:
vector = torch.tensor([12,34,3])

In [10]:
vector.ndim

1

In [11]:
# random tensor 
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3467, 0.5144, 0.0322, 0.0591],
        [0.3573, 0.4703, 0.9503, 0.1092],
        [0.9654, 0.0369, 0.4233, 0.5121]])

In [12]:
random_image_size_tensor = torch.rand(224,224,3)

In [13]:
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [14]:
random_tansor = torch.rand(3,4)
random_tensor

tensor([[0.3467, 0.5144, 0.0322, 0.0591],
        [0.3573, 0.4703, 0.9503, 0.1092],
        [0.9654, 0.0369, 0.4233, 0.5121]])

In [15]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# usiing arange function 
one_to_ten = torch.arange(start=1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# creating tensor using like 

ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
#detail about tensor 
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3227, 0.7512, 0.8106, 0.9061],
        [0.0252, 0.4512, 0.6980, 0.3890],
        [0.8747, 0.0278, 0.0481, 0.9582]])

In [20]:
# showing details about tensor 
print(f"tensor datatype {some_tensor.dtype}")
print(f"tensor shape {some_tensor.shape}")
print(f"device that tensor is on {some_tensor.device}")

tensor datatype torch.float32
tensor shape torch.Size([3, 4])
device that tensor is on cpu


In [22]:
#create tensor 
tensor = torch.tensor([2,3,4])
tensor +19

tensor([21, 22, 23])